version: '2'

services:
  has-to-be-rating-charge-process-app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - APP_ENV=prod
      - APP_DEBUG=false
    volumes:
      - '.:/app'
